In [4]:
import csv
file=open("nyc_weather.csv")
data=csv.reader(file)
data_list=list(data)
for row in data_list:
    for column in row:
        print(column,"\t",end=" ")
    print()

EST 	 Temperature 	 DewPoint 	 Humidity 	 Sea Level PressureIn 	 VisibilityMiles 	 WindSpeedMPH 	 PrecipitationIn 	 CloudCover 	 Events 	 WindDirDegrees
1/1/2016 	 38 	 23 	 52 	 30.03 	 10 	 8 	 0 	 5 	  	 281
1/2/2016 	 36 	 18 	 46 	 30.02 	 10 	 7 	 0 	 3 	  	 275
1/3/2016 	 40 	 21 	 47 	 29.86 	 10 	 8 	 0 	 1 	  	 277
1/4/2016 	 25 	 9 	 44 	 30.05 	 10 	 9 	 0 	 3 	  	 345
1/5/2016 	 20 	 -3 	 41 	 30.57 	 10 	 5 	 0 	 0 	  	 333
1/6/2016 	 33 	 4 	 35 	 30.5 	 10 	 4 	 0 	 0 	  	 259
1/7/2016 	 39 	 11 	 33 	 30.28 	 10 	 2 	 0 	 3 	  	 293
1/8/2016 	 39 	 29 	 64 	 30.2 	 10 	 4 	 0 	 8 	  	 79
1/9/2016 	 44 	 38 	 77 	 30.16 	 9 	 8 	 T 	 8 	 Rain 	 76
1/10/2016 	 50 	 46 	 71 	 29.59 	 4 	  	 1.8 	 7 	 Rain 	 109
1/11/2016 	 33 	 8 	 37 	 29.92 	 10 	  	 0 	 1 	  	 289
1/12/2016 	 35 	 15 	 53 	 29.85 	 10 	 6 	 T 	 4 	  	 235
1/13/2016 	 26 	 4 	 42 	 29.94 	 10 	 10 	 0 	 0 	  	 284
1/14/2016 	 30 	 12 	 47 	 29.95 	 10 	 5 	 T 	 7 	  	 266
1/15/2016 	 43 	 31 	 62 	 29.82 	 9 	 5 	 T 	 2 	  	 101
1/16/2016 	 47 	 37 	 70 	 29.52 	 8 	 7 	 0.24 	 7 	 Rain 	 340
1/17/2016 	 36 	 23 	 66 	 29.78 	 8 	 6 	 0.05 	 6 	 Fog-Snow 	 345
1/18/2016 	 25 	 6 	 53 	 29.83 	 9 	 12 	 T 	 2 	 Snow 	 293
1/19/2016 	 22 	 3 	 42 	 30.03 	 10 	 11 	 0 	 1 	  	 293
1/20/2016 	 32 	 15 	 49 	 30.13 	 10 	 6 	 0 	 2 	  	 302
1/21/2016 	 31 	 11 	 45 	 30.15 	 10 	 6 	 0 	 1 	  	 312
1/22/2016 	 26 	 6 	 41 	 30.21 	 9 	  	 0.01 	 3 	 Snow 	 34
1/23/2016 	 26 	 21 	 78 	 29.77 	 1 	 16 	 2.31 	 8 	 Fog-Snow 	 42
1/24/2016 	 28 	 11 	 53 	 29.92 	 8 	 6 	 T 	 3 	 Snow 	 327
1/25/2016 	 34 	 18 	 54 	 30.25 	 10 	 3 	 0 	 2 	  	 286
1/26/2016 	 43 	 29 	 56 	 30.03 	 10 	 7 	 0 	 2 	  	 244
1/27/2016 	 41 	 22 	 45 	 30.03 	 10 	 7 	 T 	 3 	 Rain 	 311
1/28/2016 	 37 	 20 	 51 	 29.9 	 10 	 5 	 0 	 1 	  	 234
1/29/2016 	 36 	 21 	 50 	 29.58 	 10 	 8 	 0 	 4 	  	 298
1/30/2016 	 34 	 16 	 46 	 30.01 	 10 	 7 	 0 	 0 	  	 257
1/31/2016 	 46 	 28 	 52 	 29.9 	 10 	 5 	 0 	 0 	  	 241

In [5]:
import pandas as pd
df=pd.read_csv("nyc_weather.csv")
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333